server:
  port: 12312

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 30MB

retrofit:
  global-retry:
    enable: true
