springdoc:
  swagger-ui:
    path: /swagger-ui.html
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  mail:
    properties:
      mail:
        debug: true

retrofit:
  global-log:
    log-strategy: body
