server:
  port: 12312

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 30MB
  flyway:
    locations: classpath:migrations/{vendor}
    table: t_migrations
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    from: ${SMTP_FROM}
    from-name: ${SMTP_FROM_NAME}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  server:
    port: 9999
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

retrofit:
  global-log:
    log-strategy: basic
  global-retry:
    enable: true
    interval-ms: 3000
    max-retries: 3
  global-timeout:
    connect-timeout-ms: 3_000
    read-timeout-ms: 60_000
    write-timeout-ms: 60_000
