name: CI

on:
  workflow_dispatch:

jobs:
  build-for-lpg-web:
    name: Build lpg-web
    runs-on: self-hosted
    steps:
      - name: Checkout lpg-web
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/lpg-web
          ref: master
          persist-credentials: false
          fetch-depth: 0
          path: lpg-web

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "8"
          run_install: false

      - name: Get pnpm store directory
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

